In [8]:
import numpy as np
a=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(a)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.ndim) #number of dimensions

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
int64
2


In [11]:
a=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b=np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])
print(a+b)
print(a-b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [10]:
import pandas as pd
c=pd.DataFrame(a)
print(c)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
